version: '3'

volumes:
  prod_pointy_data: {}
  prod_pointy_data_backups: {}
  prod_redis_data: {}

services:
  redis:
    image: redis
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - prod_redis_data:/data
    ports:
      - "6379:6379"
  db:
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    restart: always
    image: postgres:12
    expose:
      - "5432"
    volumes:
      - prod_pointy_data:/var/lib/postgresql/data
      - prod_pointy_data_backups:/backups
  api:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    links:
      - db:db
    environment:
      REDIS_HOST: "redis://redis:6379/0"
    ports:
      - "8000:8000"
  web:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
