# Playbook to run one time to set up the cluster
---
- hosts: k8s
  vars:
    ansible_connection: local
    ansible_python_interpreter: "{{ ansible_playbook_python }}"
  roles:
  - role: caktus.k8s-web-cluster
