# Use -e VARNAME="expression to output the value of" -e OUTPUTFILENAME="filename to put the value into"
- hosts: all
  vars:
    ansible_connection: local
    ansible_python_interpreter: "{{ ansible_playbook_python }}"
  tasks:
    - name: first create a template that'll dump our variable
      template:
        src: dump_variable_metatemplate.j2
        dest: dump_variable_template.j2
    - name: now expand *that* template to find out the value of our variable/expression
      template:
        src: dump_variable_template.j2
        dest: "{{ OUTPUTFILENAME }}"
    - name: cleanup
      file:
        state: absent
        path: dump_variable_template.j2
