#
# Common configuration variables for all environments
# being deployed to Kubernetes.
#
app_name: pointy
ansible_connection: local
python_version: 3.8
less_version: 2.1.0

##########################

# pointy-EKS stack outputs:
ClusterEndpoint: "https://74406E3AD450E7845D0EF653E7C6F020.gr7.us-west-2.eks.amazonaws.com" # The connection endpoint for the EKS cluster API. -
DatabaseAddress: "pd1mkme64jqsopw.cfndmcylfosz.us-west-2.rds.amazonaws.com" # The connection endpoint for the database. -
DatabasePort: 5432 # The port number on which the database accepts connections. -
DatabaseURL: "postgres://pointy:_PASSWORD_@pd1mkme64jqsopw.cfndmcylfosz.us-west-2.rds.amazonaws.com:5432/pointy" # URL to connect (without the password) to the database. -
RepositoryURL: "354308461188.dkr.ecr.us-west-2.amazonaws.com" # The docker repository URL

##########################

aws_region: "us-west-2"
eks_registry: "{{ RepositoryURL }}"
k8s_cluster_name: "pointy-EKS-cluster"
k8s_container_image: "{{ eks_registry }}/pointy"

k8s_auth_host: "{{ ClusterEndpoint }}"
k8s_auth_ssl_ca_cert: "k8s_auth_ssl_ca_cert.txt"

##########################

# ----------------------------------------------------------------------------
# caktus.k8s-web-cluster: Configure kubernetes cluster for web apps
# Some of these variables need the same values as other variables, just have different names.
# ----------------------------------------------------------------------------

k8s_cluster_type: aws
k8s_letsencrypt_email: pointy-team@caktusgroup.com
##############################

k8s_container_name: "{{ app_name }}-web"
k8s_container_port: 8000

LETSENCRYPT_EMAIL: pointy-team@caktusgroup.com
CLUSTER_TYPE: "aws"

# No underscores in namespace...
k8s_namespace: "{{ app_name }}-{{ env_name }}"

k8s_container_image_pull_policy: Always

# pointy uses practically everything except elasticsearch
k8s_elasticsearch_enabled: false
k8s_memcached_enabled: true
k8s_redis_enabled: true
k8s_worker_enabled: true
k8s_worker_beat_enabled: true

# Note: if just the EKS cluster is going to access the registry, it
# has access by default and we don't need to set up registry
# secrets in our K8S cluster.
# We might still need to auth somehow if we need to push to the registry from
# our own systems, of course.
k8s_dockerconfigjson: {}
