#
# Common configuration variables for all environments
# being deployed to Kubernetes.
#
app_name: pointy
ansible_connection: local

##########################

# pointy-EKS stack outputs:
ClusterEndpoint: "https://A9ED894F5721970831AED9882203CA29.gr7.us-east-1.eks.amazonaws.com" # The connection endpoint for the EKS cluster API. -
DatabaseAddress: "cdxeo4fjae7bwu.ckpm6k1hp413.us-east-1.rds.amazonaws.com" # The connection endpoint for the database. -
RepositoryURL: "472354598015.dkr.ecr.us-east-1.amazonaws.com" # The docker repository URL

##########################

aws_region: "us-east-1"
eks_registry: "{{ RepositoryURL }}"
k8s_container_image: "{{ eks_registry }}/pointy"

k8s_auth_host: "{{ ClusterEndpoint }}"
k8s_auth_ssl_ca_cert: "k8s_auth_ssl_ca_cert.txt"
k8s_namespace: "{{ app_name }}-{{ env_name }}"

##########################

# pointy-web
k8s_container_name: "{{ app_name }}-web"
k8s_container_port: 80
k8s_container_image_pull_policy: Always

# pointy uses practically everything except elasticsearch
k8s_redis_enabled: true

# Note: if just the EKS cluster is going to access the registry, it
# has access by default and we don't need to set up registry
# secrets in our K8S cluster.
# We might still need to auth somehow if we need to push to the registry from
# our own systems, of course.
k8s_dockerconfigjson: {}
