# Generated by Django 3.0.5 on 2020-04-10 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PointyRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('session_id', models.CharField(max_length=512, unique=True)),
                ('admin_name', models.CharField(max_length=512)),
                ('values_template_id', models.IntegerField()),
                ('phase', models.CharField(max_length=512)),
                ('last_access_dt', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='RoomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=512)),
                ('vote', models.CharField(blank=True, default='', max_length=512)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='core.PointyRoom')),
            ],
            options={
                'unique_together': {('room', 'username')},
            },
        ),
        migrations.CreateModel(
            name='RoomTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('final_vote', models.CharField(blank=True, default='', max_length=512)),
                ('last_update_dt', models.DateTimeField()),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='core.PointyRoom')),
            ],
            options={
                'ordering': ('-last_update_dt',),
                'unique_together': {('room', 'name')},
            },
        ),
    ]
